theforeman/puppet-qpid

.travis.yml
Gemfile
manifests/router/config.pp
manifests/router/link_route_pattern.pp
spec/classes/qpid_router_config_spec.rb
templates/router/link_route_pattern.conf.erb

In order to actually connect an on-demand connector, we need to have support for `linkRoutePatterns`

refs #8175 - Add linkRoutePattern support for dispatch router

---

manifests/params.pp

The qpid-tools package is a client-side package that is installed by other
modules and can cause conflicts if it is listed here. It is not needed for a
server install.

remove qpid-tools package

---

manifests/config.pp

The value defaults to [] already. No need to create an array of arrays.

Removes brackets around user_group parameter

---

manifests/install.pp
manifests/params.pp
manifests/tools.pp
spec/classes/qpid_tools_spec.rb

Some module, such as Pulp, need to ensure the qpid_tools package
is present on a system. This creates a class to isolate qpid tools
to be used by this module and others.

Add qpid::tools package

---

manifests/params.pp

The validate_re method expects a string and not an integer to be
pased to it. The integer value causes tests to fail on modules
that depend upon this qpid module.

Change ssl_port to a string

---

manifests/params.pp

And conflicts with other package that we manage separately. We are trying to keep this package updated on our own, even on machines that don't have this qpid package.

don't manage policycoreutils-python, as it is not related to qpid

---

spec/classes/qpid_router_config_spec.rb
templates/router/log.conf.erb

Otherwise:
Oct 14 07:57:49 qpid-asymmetric.example.com qdrouterd[25485]: Fri Oct 14 07:57:49 2016 ERROR (error) Python: Exception: Cannot load configuration file /etc/qpid-dispatch/qdrouterd.conf: org.apache.qpid.dispatch.log: Unknown attribute 'enabled' for 'org.apache.qpid.dispatch.log'

Dispatch router log option is 'enable' not 'enabled'

---

manifests/init.pp

Qpid is probably going into the top-level of the installer with
the removal of puppet-capsule, so we need to ensure the installer
--help isn't growing out of control.  This hides everything but
log-level, the only setting a katello user will really need
to touch.
For non-katello users, this has the benefit of categorizing the
params and making it a bit easier to use.

Move parameters into categories

---

.fixtures.yml
manifests/init.pp
manifests/params.pp
manifests/router.pp
manifests/router/params.pp
manifests/router/service.pp
metadata.json
spec/classes/qpid_config_spec.rb
spec/classes/qpid_router_config_spec.rb
templates/qpidd.conf.erb

When you have significant numbers of qpid or qdrouterd connections,
you need to set max-connections for qpid, and increase the number
of open files for qdrouterd.

Configure performance tuning settings for qpid

---

manifests/config/bind.pp
manifests/config/exchange.pp
manifests/config_cmd.pp
spec/defines/bind_spec.rb
spec/defines/exchange_spec.rb

Moves away from having a bind action to a specific exchange and allows
using bind as a generic type as defined by qpid. This change now requires
exchange to be specified.
Ref: https://qpid.apache.org/releases/qpid-0.32/cpp-broker/book/chapter-Managing-CPP-Broker.html

Re-factor bind_event to the generic bind action

---

manifests/config/bind.pp
manifests/config/exchange.pp
manifests/config_cmd.pp
spec/defines/bind_spec.rb
spec/defines/config_cmd_spec.rb
spec/defines/exchange_spec.rb

* Makes the dependency on Service[qpidd] optional
* Documents the $unless parameter
* Removes the hardcoded defaults from candlepin::config::*
* Adds tests

config_cmd: optional qpidd, documentation, tests

---

manifests/config/bind.pp
spec/defines/bind_spec.rb

Before:
[root@centos7-katello-nightly config]# qpid-config --ssl-certificate=/etc/pki/katello/qpid_client_striped.crt -b amqps://localhost:5671 list binding|grep katello_event_queue
katello_event_queue                                                           katello_event_queue
After:
[root@centos7-katello-nightly config]# qpid-config --ssl-certificate=/etc/pki/katello/qpid_client_striped.crt -b amqps://localhost:5671 list binding|grep katello_event_queue 
katello_event_queue                                                           katello_event_queue                                                           0           {}         
katello_event_queue                                                           compliance.created                                                            0 …

Fixes #18812 - update puppet logic on qpid bind

---

manifests/install.pp

qpid-tools installs a compat package that blocks client and server if theyre not installed first, fixes #46

Package conflicts during install on CentOS7, fixes #46

---

manifests/config_cmd.pp

`qpid-config` is part of `qpid-tools` package. This PR ensures `qpid-tools` are actually installed.

ensure config_cmd has qpid-tools installed

---

manifests/router/service.pp
manifests/service.pp
spec/classes/qpid_router_config_spec.rb
spec/classes/qpid_spec.rb
spec/spec_helper.rb

This now allows the purging of systemd limits. It also removes a duplicate restart.
Should replace https://github.com/theforeman/puppet-qpid/pull/95

Properly handle systemd_limits

---

manifests/client.pp
manifests/client/params.pp
manifests/config.pp
manifests/config/bind.pp
manifests/config/exchange.pp
manifests/config/queue.pp
manifests/config_cmd.pp
manifests/install.pp
manifests/params.pp
manifests/router.pp
manifests/router/config.pp
manifests/router/connector.pp
manifests/router/install.pp
manifests/router/link_route.pp
manifests/router/listener.pp
manifests/router/log.pp
manifests/router/params.pp
manifests/router/service.pp
manifests/router/ssl_profile.pp
manifests/service.pp

This leaves out init since that actually uses parameter groups and yardoc has no support for this. Should I convert it anyway for a proper reference manual?

Refactor docs from yardoc to rdoc

---

manifests/service.pp
spec/classes/qpid_spec.rb
templates/wait-for-port.conf.erb

qpidd does not open the ssl-port immediately after starting, but after
some initialization happened. Let's make qpidd.service not return until
the port is really open, as otherwise actions depending on the service
being available might fail

Fixes #25909 - make qpidd.service wait until the port is open

---

metadata.json

we're using `systemd::service_limits` which was introduced in 1.0.0:
* [changelog for 1.0.0](https://github.com/camptocamp/puppet-systemd/blob/master/CHANGELOG.md#100-2017-09-04)
* [commit that added the functionality](https://github.com/camptocamp/puppet-systemd/commit/ec94e54f14c214a5423681e90b99d6e73094bfeb)

bump camptocamp/systemd requirement to >= 1.0.0

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
manifests/router/connector.pp
spec/classes/qpid_spec.rb
spec/defines/router_connector_spec.rb
templates/qpidd.conf.erb
templates/router/connector.conf.erb

Consider testing in conjunction with:
https://github.com/theforeman/puppet-katello/pull/283
https://github.com/theforeman/puppet-foreman_proxy_content/pull/197
To test (assumes forklifted dev env):
- follow forklift docs (https://github.com/theforeman/forklift/blob/master/docs/development.md#test-puppet-module-pull-requests) to test the linked PRs
- 'vagrant provision centos7-katello-devel'
- verify that /etc/qpid/qpid.acl is populated according to the PR
- verify that /etc/qpid-dispatch/qdrouter.conf "connector" has sasl-mechanism PLAIN, sasl-username katello_agent and sasl-password that resembles a password
- verify that services qpidd and qdrouterd are running properly
- register a client, verify that package actions can be performed as usual via katello-agent
scripts should not be …

Refs #26571 - Support ACL file & router auth

---

manifests/params.pp

This is typically needed by service interacting with qpidd and not
qpidd itself.
@ekohl you were right :)

Drop python2-qpid as a server package

---

metadata.json

stdlib 6.0.0 is due to be released soon.
This module has already dropped support for puppet 4.
See
https://github.com/puppetlabs/puppetlabs-stdlib/blob/217068f97edd2396ce37ac8c1bd7e23da621d6be/CHANGELOG.md#supported-release-600

Allow `puppetlabs/stdlib`  and `puppetlabs/concat` 6.x

---

spec/classes/qpid_spec.rb
templates/wait-for-port.conf.erb

Given a machine that has 127.0.0.1 / ::1 on lo and eth0 has 2001:db::1, in other works, no IPv4 connectivity, then qpid qpid binds only on IPv6, even when a host needs to listen on localhost. Since netcat can connect to either, it is a safe check.
@adamruzicka this is currently a draft since I haven't tested this yet. Could you give this a spin in your setup?

Fixes #28672 - Check if qpid is up using localhost

---

metadata.json

puppet-blacksmith assumes the author and the module name match case.  This also matches to the actual forge username.

Match author case in metadata

---

manifests/service.pp
spec/classes/qpid_spec.rb
templates/wait-for-port.conf.erb

The current method can result in journal error messages:
[System] error Error reading socket: Encountered end of file [-5938]
This updated version waits and checks for listening ports
and greps for the port in question to appear before signaling
that the service is ready.

Fixes #30252: Make wait for port more resilient

---

CHANGELOG.md
HISTORY.md
metadata.json

This removes some of the confusing parts of this module, like we have a 6.2-stable branch that's essentially ahead of this module. It'll be a bit painful to update all modules to allow this new release but in the end it'll be clearer when we can use master as a development branch.

Release 7.0.0

---

manifests/install.pp
spec/classes/qpid_spec.rb

The qpidd service relation is already set in init.pp. The direct package resource is replaced with the class that encapsulates it.

Remove duplicate relations

---

manifests/install.pp
spec/classes/qpid_spec.rb

Given the SASL mechanisms used, the cyrus-sasl-plain package is
needed to support them.
This allows us to remove this requirement from the katello package spec file and localize it with the code that needs it. This further helps when we make katello-agent infrastructure optional as we will only install this package when its needed.

Install cyrus-sasl-plain package

---

spec/classes/qpid_router_spec.rb
templates/router/header.conf.erb

The header.conf.erb template was referencing router_mode instead
of the 'mode' parameter which can be set by users. Therefore the
mode could never actually be configured by a user and the default
in params.pp was always used.

Router template should use mode and not router_mode

---

manifests/config.pp
manifests/install.pp
manifests/router/service.pp
manifests/service.pp
spec/classes/qpid_spec.rb

Addresses feedback from previous commit 734b44b8dd2061743f0b12695482ac691682deb5
to not remove ancillary packages and ensure relationship between user
and group.
Attempts to address feedback from https://github.com/theforeman/puppet-qpid/pull/154. This does not currently address https://github.com/theforeman/puppet-qpid/pull/154#discussion_r607744116 as there is discussion around it.

Refs #32037: Do not remove all packages when ensuring absent

---

spec/acceptance/qpid_tool_spec.rb

With 734b44 we added this regression test for an old issue where qpid-tools installed
compat-qpid-cpp-client that blocked other package installs. After further discussion
we decided this test no longer makes sense to keep around.

Drop Package['qpit-tools'] -> Package['qpid-cpp-server'] test case

---

README.md
spec/defines/router_link_route_spec.rb
spec/defines/router_log_spec.rb
spec/defines/router_ssl_profile_spec.rb
templates/router/link_route.conf.erb
templates/router/log.conf.erb
templates/router/ssl_profile.conf.erb

Attribute 'certDb' of entity 'sslProfile' has been deprecated. Use 'caCertFile' instead
Attribute 'keyFile' of entity 'sslProfile' has been deprecated. Use 'privateKeyFile' instead
Attribute 'dir' of entity 'linkRoute' has been deprecated. Use 'direction' instead
Attribute 'timestamp' of entity 'log' has been deprecated. Use 'includeTimestamp' instead
Attribute 'output' of entity 'log' has been deprecated. Use 'outputFile' instead

Fix qpid-dispatch parameter deprecation warnings

---

manifests/config.pp
manifests/init.pp
spec/acceptance/qpid_spec.rb
spec/classes/qpid_spec.rb
templates/qpidd.conf.erb

When the qpidd service starts it creates a directory /var/lib/qpidd/.qpidd
If the qpid is then ensured to be absent, removing the qpidd user
and then re-enabled this directory will have the wrong user id set on it
and get permission denied when trying to start the service.

Refs #32037: Manage /var/lib/qpidd
